### ISSUE TITLE
Phase I / Beta Distribution Limits

### ISSUE THREAD

**Issue by TMiguelT** [dionresearch/hotelling#7]
Tracy et al., 1992 [1] discuss how the F-distribution control limits are only valid in phase II SPC, ie when the incoming samples are independent from those used to calculate the in-control distribution. It might be helpful to add the phase I control limits too, as this is a useful application of Hotelling control charts.

[1] Tracy, N. D., Young, J. C., & Mason, R. L. (1992). Multivariate Control Charts for Individual Observations. Journal of Quality Technology, 24(2), 88–95. https://doi.org/10.1080/00224065.1992.12015232

**Comment by fdion** [comment]
Thanks for your comment @TMiguelT 

`Hotelling` uses beta distribution for phase I. I reviewed the documentation and there is an explanation of this here (under `control_interval`): https://dionresearch.github.io/hotelling/modules.html#module-hotelling.plots

> For Hotelling control charts, phase 1 is using Qi. This follows a beta distribution, not an F distribution. For
>    phase 2 uses future observations. These would follow a known distribution ~ F (Seber, 1984).
>    The lower and upper lines are based on the quantiles of the distribution (aka percent point function)
>    for α and 1 - α, while the center line is the median (50%).
>
>    See:
>        - Seber, G (1984). Multivariate Observations. John Wiley & Sons.
>        - Nola D. Tracy, John C. Young & Robert L. Mason (1992) Multivariate Control Charts for individual Observations,
>          Journal or Quality Technology, 24:2, 88-95, DOI:10.1080/00224065.1992.12015232

It will also show if you type `help(control_interval)` in `python` or `ipython` or a `jupyter` notebook.

Perhaps this should be made a bit clearer as front matter? If you could take a look at the current documentation and let me know your suggestion to make this clearer.

I do have several items I need to add to the documentation anyway, so that's good timing.

**Comment by TMiguelT** [comment]
That's my bad, I was looking at the `stats.hotelling_t2` rather than `plots.control_interval`. Some extra documentation certainly couldn't hurt. Thanks for the answer!
