### ISSUE TITLE
Does one need to preprocess data, i.e. z-norm, before feeding into `hotelling_t2` function?

### ISSUE THREAD

**Issue by hovinh** [dionresearch/hotelling#8]
Hi Dion,

I have a question about using `hotelling_t2()` function directly. I would like to ask if one need to preprocess data before feeding it into this function?
- I've had a look at your code and can't seem to find the code snippet relevant to this. If yes, could you please provide me with the details?
- That said, I have tried to feed in the (impurities, temp, concentration) dataset with/without z-norm and the resulting MVA chart stays fixed. Could you please share more about how it works? Would the `hotelling_t2()` still perform well even if data in different features (columns) have a different range?

Thank you.
Sincerely,
Vinh

**Comment by fdion** [comment]
Hi, good question. The answer is, it depends 😄 

Just like PCA or SVM usually need normalization, you might need normalization / scaling with Hotelling. Having said that, it comes down to your requirements.

**Comment by hovinh** [comment]
Thank you. I'm curious because I plan to make a small comparison between all hotellingT2 packages that I can find on Github. So, in the hope to have an apple-to-apple setting, I put up this question. 

Thank you again, and I think this thread can be closed. However, it would be great to have any input from you on this little experiment of mine :D

**Comment by fdion** [comment]
@hovinh I just re-read your question, and I have to qualify my answer a bit more.

If you are using T2 as a measure against a zero mean (specifying only `x`), perhaps to use it as an absolute "distance" metric (as part of a machine learning model), it _usually_ makes sense to scale to 1.

If you are comparing two samples from the same population, same units, then scaling will not have any impact on the result. That's because you are now calculating T2 for two samples, or one sample against a known mean. 

I hope this makes sense.
